CREATE TABLE GHANA_CARD (
	GHANA_CARD_ID VARCHAR PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	PREVIOUS_NAMES VARCHAR(50) DEFAULT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(50) NOT NULL,
	HEIGHT_IN_METRES VARCHAR(5) NOT NULL,
	COUNTRY_OF_ORIGIN VARCHAR(150) NOT NULL,
	CARD_ISSUE_DATE DATE NOT NULL,
	PLACE_OF_ISSUE VARCHAR(150) NOT NULL,
	CARD_EXPIRY_DATE DATE NOT NULL,
	DOCUMENT_NUMBER VARCHAR UNIQUE NOT NULL,
	PICTURE_OF_PERSON BYTEA NOT NULL, --Store jpegs and other file formats--
	BIOMETRICS_OF_PERSON BYTEA --Store biometric data such as fingerprint and retina scans--
);

SELECT
	*
FROM
	GHANA_CARD;

INSERT INTO GHANA_CARD VALUES(
);

DROP TABLE GHANA_CARD;

DELETE FROM GHANA_CARD;

CREATE TABLE VOTER_ID_CARD (
	VOTER_ID SERIAL,
	GHANA_CARD_ID VARCHAR NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(50) NOT NULL,
	REGISTRATION_DATE DATE NOT NULL,
	POLLING_STATION_CODE VARCHAR(50) NOT NULL,
	PICTURE_OF_PERSON BYTEA DEFAULT NULL,
	BIOMETRICS_OF_PERSON BYTEA DEFAULT NULL,
	FOREIGN KEY (GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT
);

SELECT
	*
FROM
	VOTER_ID_CARD;

INSERT INTO VOTER_ID_CARD VALUES(
);

DROP TABLE VOTER_ID_CARD;

DELETE FROM VOTER_ID_CARD;

CREATE TABLE DRIVER_LICENSE (
	DRIVER_LICENSE_ID VARCHAR(60) DEFAULT NULL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(50) DEFAULT NULL,
	HEIGHT_IN_METRES VARCHAR(5) NOT NULL,
	COUNTRY_OF_ORIGIN VARCHAR(150) NOT NULL,
	LICENSE_REGISTRATION_DATE DATE NOT NULL,
	REGISTRATION_PLACE VARCHAR(150) NOT NULL,
	LICENSE_EXPIRY_DATE DATE NOT NULL,
	CAR_NUMBER_PLATE VARCHAR(50) NOT NULL,
	PICTURE_OF_PERSON BYTEA DEFAULT NULL,
	FOREIGN KEY(GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT
);

SELECT
	*
FROM
	DRIVER_LICENSE;

INSERT INTO DRIVER_LICENSE VALUES(
);

DROP TABLE DRIVER_LICENSE;

DELETE FROM DRIVER_LICENSE;

CREATE TABLE PASSPORT (
	PASSPORT_ID VARCHAR DEFAULT NULL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL PRIMARY KEY,
	VOTER_ID VARCHAR(60) DEFAULT NULL,
	DRIVER_LICENSE_ID VARCHAR(60) DEFAULT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	COUNTRY_OF_ORIGIN VARCHAR(150) NOT NULL,
	COUNTRY_OF_RESIDENCE VARCHAR(150) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(30) DEFAULT NULL,
	MOBILE_NUMBER VARCHAR(50) NOT NULL,
	MARITAL_STATUS VARCHAR(10) NOT NULL,
	HEIGHT_IN_METRES VARCHAR(5) NOT NULL,
	OCCUPATION VARCHAR (150) NOT NULL,
	HIGHEST_EDUCATIONAL_LEVEL VARCHAR(10) NOT NULL,
	HIGHEST_EDUCATIONAL_DEGREE_OBTAINED VARCHAR(10) NOT NULL,
	NAME_OF_FATHER VARCHAR (50) DEFAULT NULL,
	NAME_OF_MOTHER VARCHAR(50) DEFAULT NULL,
	PROFESSION_OF_FATHER VARCHAR(150) DEFAULT NULL,
	PROFESSION_OF_MOTHER VARCHAR(150) DEFAULT NULL,
	VALID_NATIONAL_CARD VARCHAR(25) NOT NULL,
	NATIONAL_CARD_ID VARCHAR NOT NULL,
	DATE_OF_ISSUE_OF_PASSPORT DATE NOT NULL,
	PLACE_OF_ISSUE_OF_PASSPORT VARCHAR(150) DEFAULT NULL,
	PASSPORT_DATE_OF_EXPIRY DATE NOT NULL,
	MOBILE_NUMBER_OF_FATHER VARCHAR(30) DEFAULT NULL,
	MOBILE_NUMBER_OF_MOTHER VARCHAR(30) DEFAULT NULL,
	PICTURE_OF_PERSON BYTEA DEFAULT NULL,
	BIOMETRICS_OF_PERSON BYTEA DEFAULT NULL,
	FOREIGN KEY (GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT,
	FOREIGN KEY (VOTER_ID) REFERENCES VOTER_ID_CARD(GHANA_CARD_ID) ON DELETE RESTRICT,
	FOREIGN KEY (DRIVER_LICENSE_ID) REFERENCES DRIVER_LICENSE(GHANA_CARD_ID) ON DELETE RESTRICT
);

INSERT INTO PASSPORT VALUES(
);

SELECT
	*
FROM
	PASSPORT;

DROP TABLE PASSPORT;

DELETE FROM PASSPORT;

SELECT
	GHANA_CARD.GHANA_CARD_ID,
	GHANA_CARD.FIRST_NAME,
	GHANA_CARD.LAST_NAME,
	PASSPORT.VOTER_ID,
	PASSPORT.DRIVER_LICENSE_ID,
	PASSPORT.PASSPORT_ID
FROM
	GHANA_CARD
	JOIN PASSPORT
	ON GHANA_CARD.GHANA_CARD_ID=PASSPORT.GHANA_CARD_ID CREATE TABLE POLICE_RECORDS (POLICE_ID_NUMBER SERIAL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL PRIMARY KEY,
	VOTER_ID VARCHAR(60) DEFAULT NULL,
	DRIVER_LICENSE_ID VARCHAR(100) DEFAULT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	COUNTRY_OF_ORIGIN VARCHAR(150) NOT NULL,
	COUNTRY_APPREHENDED VARCHAR(150) DEFAULT NULL,
	HEIGHT_IN_METRES VARCHAR(5) NOT NULL,
	OCCUPATION VARCHAR(150) DEFAULT NULL,
	GENDER VARCHAR(50) DEFAULT NULL,
	MARITAL_STATUS VARCHAR (10) DEFAULT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	CRIME_COMMITTED VARCHAR(255) DEFAULT NULL,
	DATE_PROCESSED_TO_POLICE_STATION DATE DEFAULT NULL,
	LOCATION_OF_POLICE_STATION_PROCESSED_AT VARCHAR(150) DEFAULT NULL,
	BAIL_AMOUNT_PAID_IN_LOCAL_CURRENCY INT DEFAULT 0,
	DATE_TAKEN_TO_COURT DATE DEFAULT NULL,
	NUMBER_OF_ACCOMPLICES_TO_CRIME INT DEFAULT 0,
	NAMES_OF_ACCOMPLICES_TO_CRIME VARCHAR(500) DEFAULT NULL,
	COUNTRY_TRIED VARCHAR(150) DEFAULT NULL,
	LAWYER_FOR_DEFENDANT VARCHAR(100) DEFAULT NULL,
	VERDICT_BY_COURT VARCHAR(10) DEFAULT NULL,
	CRIME_SENTENCE VARCHAR(100) DEFAULT NULL,
	NUMBER_OF_YEARS_IN_JAIL VARCHAR (4) DEFAULT NULL,
	LOCATION_OF_COURT VARCHAR (150) DEFAULT NULL,
	TYPE_OF_COURT VARCHAR(100) DEFAULT NULL,
	DATE_RELEASED_FROM_POLICE_STATION DATE DEFAULT NULL,
	DATE_RELEASED_FROM_PRISON DATE DEFAULT NULL,
	PICTURE_OF_PERSON BYTEA DEFAULT NULL,
	FOREIGN KEY(GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT,
	FOREIGN KEY(VOTER_ID) REFERENCES VOTER_ID_CARD(GHANA_CARD_ID) ON DELETE RESTRICT,
	FOREIGN KEY(DRIVER_LICENSE_ID) REFERENCES DRIVER_LICENSE(GHANA_CARD_ID) ON DELETE RESTRICT );

DROP TABLE POLICE_RECORDS;

CREATE TABLE BANK_DETAILS (
	BANK_ID SERIAL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	GENDER VARCHAR(50) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	PLACE_OF_BIRTH VARCHAR(50) NOT NULL,
	HOMETOWN VARCHAR(75) NOT NULL,
	REGION VARCHAR(75) NOT NULL,
	CITY_OR_TOWN VARCHAR(75) NOT NULL,
	RESIDENTIAL_ADDRESS VARCHAR(100) NOT NULL,
	GPS_ADDRESS VARCHAR(50) DEFAULT NULL,
	COUNTRY_OF_ORGIGIN VARCHAR(150) NOT NULL,
	COUNTRY_OF_RESIDENCE VARCHAR(150) NOT NULL,
	MOBILE_PHONE_NUMBER VARCHAR(30) NOT NULL,
	OCCUPATION VARCHAR(100) NOT NULL,
	BANK_BRANCH_WHERE_ACCOUNT_WAS_OPENED VARCHAR(100) NOT NULL,
	ACCOUNT_TYPE VARCHAR(25) NOT NULL,
	PURPOSE_OF_ACCOUNT VARCHAR(100) NOT NULL,
	ACCOUNT_NUMBER INT NOT NULL,
	CARD_PREFERENCES VARCHAR(50) NOT NULL,
	CARD_NUMBER VARCHAR(50) NOT NULL PRIMARY KEY,
	CARD_CVC VARCHAR(50) NOT NULL,
	CARD_DATE_OF_ISSUE DATE NOT NULL,
	CARD_EXPIRY_DATE DATE NOT NULL,
	CARD_PLACE_OF_ISSUE VARCHAR(50) NOT NULL,
	INTERNET_BANKING BOOLEAN,
	EMAIL_ADDRESS VARCHAR(150) UNIQUE,
	ACCOUNT_OPENED_WITH_OTHER_BANKS_ID SERIAL NOT NULL,
	ACCOUNT_OPENED_WITH_OTHER_BANKS_NAME VARCHAR(25) NOT NULL,
	ACCOUNT_OPENED_WITH_OTHER_BANKS_ACCOUNT_NUMBER INT NOT NULL,
	SOURCE_OF_FUNDS VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_FIRST_NAME VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_LAST_NAME VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_GENDER VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_RELATIONSHIP VARCHAR(25) NOT NULL,
	NEXT_OF_KIN_MOBILE_NUMBER VARCHAR(50) NOT NULL,
	EMPLOYER_NAME VARCHAR(150) NOT NULL,
	EMPLOYER_ADDRESS VARCHAR(150) NOT NULL,
	EMPLOYER_EMAIL_ADDRESS VARCHAR(150) UNIQUE DEFAULT NULL,
	EMPLOYER_REGION VARCHAR(150) NOT NULL,
	EMPLOYER_COUNTRY VARCHAR(150) NOT NULL,
	EMPLOYER_MOBILE_PHONE_NUMBER VARCHAR(30) DEFAULT NULL,
	EMPLOYER_OFFICE_PHONE_NUMBER VARCHAR(30) NOT NULL,
	LENGTH_OF_PERIOD_WITH_CURRENT_EMPLOYER VARCHAR(10) NOT NULL,
	SALARY_OR_EXPECTED_OUTCOME INT NOT NULL,
	LEVEL_OF_DEPOSITS_AMOUNT INT NOT NULL,
	FREQUENCY_OF_DEPOSITS VARCHAR(10) DEFAULT NULL,
	PICTURE_OF_PERSON BYTEA DEFAULT NULL,
	BIOMETRIC_OF_PERSON BYTEA DEFAULT NULL,
	FOREIGN KEY(GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT
);

DROP TABLE BANK_DETAILS;

SELECT
	*
FROM
	BANK_DETAILS;

CREATE TABLE MEDICAL_RECORDS (
	MEDICAL_RECORDS_ID SERIAL PRIMARY KEY NOT NULL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	HEIGHT_IN_METRES VARCHAR(5) NOT NULL,
	WEIGHT_IN_KILOGRAMS VARCHAR(10) NOT NULL,
	GENDER VARCHAR(30) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	COUNTRY_OF_ORIGIN VARCHAR(150) NOT NULL,
	COUNTRY_OF_RESIDENCE VARCHAR(150) NOT NULL,
	OCCUPATION VARCHAR(100) NOT NULL,
	DATE_OF_HOSPITAL_ADMISSION DATE DEFAULT NULL,
	HOSPITAL_ADMITTED_TO VARCHAR(150) NOT NULL,
	LOCATION_OF_HOSPITAL_ADMITTED_TO VARCHAR(150) NOT NULL,
	REASON_FOR_COMING_TO_HOSPITAL VARCHAR(150) NOT NULL,
	DATE_DISCHARGED_FROM_HOSPITAL DATE DEFAULT NULL,
	DISEASE_OR_CONDITION_CONTRACTED VARCHAR(200) NOT NULL,
	DISEASE_SYMPTOMS VARCHAR(500) NOT NULL,
	MEDICATIONS_PRESCRIBED_FOR_DISEASE VARCHAR(255) NOT NULL,
	HIV_STATUS VARCHAR(15) DEFAULT NULL,
	SEXUALLY_TRANSMITTED_DISEASES_HISTORY VARCHAR(500) NOT NULL DEFAULT 0,
	RED_BLOOD_CELL_COUNT VARCHAR(15) NOT NULL DEFAULT 0,
	WHITE_BLOOD_CELL_COUNT VARCHAR(15) NOT NULL DEFAULT 0,
	HEART_ATTACK_HISTORY VARCHAR(75) NOT NULL DEFAULT 0,
	STROKE_HISTORY VARCHAR(75) NOT NULL DEFAULT 0,
	BLOOD_PRESSURE VARCHAR(20) NOT NULL,
	SICKLE_CELL_HISTORY VARCHAR(25) NOT NULL,
	SICKLE_CELL_CATEGORY VARCHAR(10) NOT NULL,
	NEXT_OF_KIN_FIRST_NAME VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_LAST_NAME VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_GENDER VARCHAR(30) NOT NULL,
	NEXT_OF_KIN_PROFESSION VARCHAR(150) NOT NULL,
	NEXT_OF_KIN_RELATIONSHIP VARCHAR(50) NOT NULL,
	NEXT_OF_KIN_MOBILE_NUMBER VARCHAR(30) NOT NULL,
	NEXT_OF_KIN_OFFICE_NUMBER VARCHAR(30) NOT NULL DEFAULT 0,
	NEXT_OF_KIN_RESIDENTIAL_ADDRESS VARCHAR(150) NOT NULL,
	HOSPITAL_BILLS_PAID_IN_LOCAL_CURRENCY VARCHAR(25) NOT NULL,
	REASON_FOR_HOSPITAL_BILLS_PAID VARCHAR(500) NOT NULL,
	DATE_OF_SURGERY DATE DEFAULT NULL,
	CANCER_DIAGNOSIS BOOLEAN,
	TYPE_OF_CANCER VARCHAR(255) DEFAULT NULL,
	CANCER_TREATMENT VARCHAR(500) DEFAULT NULL,
	DATE_OF_CANCER_DIAGNOSIS DATE DEFAULT NULL,
	MENTAL_DISORDERS VARCHAR(500) DEFAULT NULL,
	DATE_DIAGNOSED_WITH_MENTAL_DISORDER DATE DEFAULT NULL,
	MENTAL_DISORDER_TREATMENT VARCHAR(500) DEFAULT NULL,
	EYE_TEST VARCHAR(150) DEFAULT NULL,
	PICTURE_OF_PERSON BYTEA DEFAULT NULL,
	BIOMETRICS_OF_PERSON BYTEA DEFAULT NULL,
	FOREIGN KEY (GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT
);

DROP TABLE MEDICAL_RECORDS;

CREATE TABLE BUSINESS_RECORDS (
	BUSINESS_ID SERIAL PRIMARY KEY NOT NULL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL,
	TAX_ID_NO VARCHAR(60) DEFAULT NULL,
	BUSINESS_NAME VARCHAR(200) NOT NULL,
	BUSINESS_LOCATION VARCHAR(150) NOT NULL,
	BUSINESS_OWNER VARCHAR(200) DEFAULT NULL,
	CEO_OF_BUSINESS_FIRST_NAME VARCHAR(50) NOT NULL,
	CEO_OF_BUSINESS_LAST_NAME VARCHAR(50) NOT NULL,
	BUSINESS_TYPE VARCHAR(100) NOT NULL,
	BUSINESS_CATEGORY VARCHAR(150) NOT NULL,
	EMPLOYER_FIRST_NAME VARCHAR(50) NOT NULL,
	EMPLOYER_LAST_NAME VARCHAR(50) NOT NULL,
	EMPLOYER_ADDRESS VARCHAR(150) NOT NULL,
	EMPLOYER_WEB_ADDRESS VARCHAR(255) UNIQUE DEFAULT NULL,
	EMPLOYER_MOBILE_NUMBER VARCHAR(30) DEFAULT NULL,
	EMPLOYER_OFFICE_NUMBER VARCHAR(30) DEFAULT NULL,
	NUMBER_OF_BUSINESS_BRANCHES INT DEFAULT 0,
	NUMBER_OF_COUNTRY_BRANCHES INT DEFAULT 0,
	NUMBER_OF_EMPLOYEES VARCHAR(15) DEFAULT 1,
	BUSINESS_START_YEAR VARCHAR(4) DEFAULT NULL,
	BUSINESS_END_YEAR VARCHAR(4) DEFAULT NULL,
	BUSINESS_REGISTRATION_DATE DATE NOT NULL,
	BUSINESS_REGISTRATION_PLACE VARCHAR(150) NOT NULL,
	MONTHLY_REVENUE_GENERATED_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	YEARLY_REVENUE_GENERATED_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	MONTHLY_PROFITS_MADE_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	YEARLY_PROFITS_MADE_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	MONTHLY_LOSSES_INCURRED_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	YEARLY_LOSSES_INCURRED_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	FOREIGN KEY(GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT
);

SELECT
	*
FROM
	BUSINESS_RECORDS;

INSERT INTO BUSINESS_RECORDS VALUES (
);

DELETE FROM BUSINESS_RECORDS;

DROP TABLE BUSINESS_RECORDS;

CREATE TABLE ACADEMIC_RECORDS (
	RECORD_ID SERIAL NOT NULL,
	GHANA_CARD_ID VARCHAR(60) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	OTHER_NAMES VARCHAR(100) DEFAULT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	HOMETOWN VARCHAR(100) DEFAULT NULL,
	COUNTRY_OF_ORIGIN VARCHAR(150) NOT NULL,
	COUNTRY_OF_RESIDENCE VARCHAR(150) NOT NULL,
	GENDER VARCHAR(30) DEFAULT NULL,
	SCHOOL_ATTENDED VARCHAR(255) DEFAULT NULL,
	SCHOOL_ENROLLMENT_DATE DATE DEFAULT NULL,
	SCHOOL_COMPLETION_DATE DATE DEFAULT NULL,
	COUNTRY_OF_SCHOOL_ATTENDED VARCHAR(150) DEFAULT NULL,
	LOCATION_OF_SCHOOL_ATTENDED VARCHAR(150) DEFAULT NULL,
	ID_NUMBER_AT_SCHOOL VARCHAR(75) NOT NULL,
	PROGRAMME_TAKEN_IN_SCHOOL VARCHAR(100) NOT NULL,
	SUBJECTS_TAKEN_UNDER_PROGRAMME VARCHAR(255) NOT NULL,
	GRADE_PER_SUBJECT VARCHAR(5),
	MARKS_SCORED_PER_SUBJECT VARCHAR(5) DEFAULT NULL,
	SCHOOL_FEES_AMOUNT_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	TOTAL_SCHOOL_FEES_AMOUNT_PAID_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	SEMESTERS_SPENT_IN_SCHOOL INT NOT NULL,
	PER_SEMESTER_DURATION VARCHAR(10) NOT NULL,
	HALL_OR_HOSTEL_APPLIED_TO VARCHAR(150) DEFAULT NULL,
	HALL_FEES_PER_YEAR_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	HALL_FEES_AMOUNT_PAID_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	SCHOOL_ACTIVITES VARCHAR(25) DEFAULT NULL,
	POSITION_HELD_IN_SCHOOL VARCHAR(255) DEFAULT NULL,
	SUBJECTS_RETAKEN INT DEFAULT NULL,
	SUBJECT_NAMES_RETAKEN VARCHAR(350) DEFAULT NULL,
	FREQUENCY_PER_SUBJECT_RETAKEN INT DEFAULT 0,
	AMOUNT_PAID_PER_SUBJECT_RETAKEN_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	FINAL_GPA_AT_COMPLETION VARCHAR(7) DEFAULT NULL,
	FOREIGN KEY(GHANA_CARD_ID) REFERENCES GHANA_CARD(GHANA_CARD_ID) ON DELETE RESTRICT
);

CREATE TABLE SHOPPING (
	SHOPPING_ID SERIAL NOT NULL,
	CARD_NUMBER VARCHAR(50) NOT NULL PRIMARY KEY, --Research on integer out of range and which data type in postgresql can store date in only month and year format
	CARD_CVC VARCHAR(5) NOT NULL,
	CARD_EXPIRY_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL_ADDRESS VARCHAR(150) UNIQUE NOT NULL,
	RESIDENTIAL_ADDRESS VARCHAR(150) NOT NULL,
	ZIP_CODE VARCHAR(20) NOT NULL,
	REGION VARCHAR(25) NOT NULL,
	COUNTRY VARCHAR(150) NOT NULL,
	MOBILE_NUMBER VARCHAR(30) DEFAULT NULL,
	SITE_PASSWORD BYTEA NOT NULL, --Research on data type for storing passwords on sql(and postgresql)
	GENDER VARCHAR(30) NOT NULL,
	DATE_AND_TIME_OF_SHOPPING TIMESTAMP NOT NULL,
	ITEM_NAME_PURCHASED VARCHAR(255) DEFAULT NULL,
	ITEM_CATEGORY VARCHAR(255) NOT NULL,
	ITEM_AVAILABILITY BOOLEAN,
	PRICE_OF_ONE_ITEM_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	ITEM_QUANTITY INT DEFAULT 0,
	SITE_OF_ITEM_PURCHASED VARCHAR(150) NOT NULL,
	PAYMENT_SYSTEM_USED_IN_ITEM_PURCHASED VARCHAR(50),
	TOTAL_AMOUNT_OF_ITEMS_PURCHASED_IN_LOCAL_CURRENCY VARCHAR(25) DEFAULT 0,
	EXPECTED_DELIVERY_DATE DATE NOT NULL,
	MODE_OF_ITEM_DELIVERY VARCHAR(20) NOT NULL,
	DISCOUNT_APPLIED_ON_ITEM VARCHAR(5) DEFAULT 0,
	DISCOUNT_APPLIED_ON_DELIVERY VARCHAR(5) DEFAULT 0,
	ITEM_WISHLIST VARCHAR(255) DEFAULT NULL,
	DEVICE_USED_FOR_SHOPPING VARCHAR(100) DEFAULT NULL,
	FOREIGN KEY(CARD_NUMBER) REFERENCES BANK_DETAILS(CARD_NUMBER) ON DELETE RESTRICT
);

SELECT
	*
FROM
	SHOPPING;

DROP TABLE SHOPPING;

INSERT INTO SHOPPING VALUES(
);

DELETE FROM SHOPPING;